infocodest/models/daily.py
"""Data models."""
# from infocodest import db
from infocodest.extensions import db


class Daily(db.Model):
    """Data model for user accounts."""

    __tablename__ = "daily"

    id = db.Column(db.Integer, primary_key=True)
    aplicacion = db.Column(db.String(64), index=False, unique=True, nullable=False)
    repo = db.Column(db.Integer, index=True, unique=True, nullable=False)
    proveedor = db.Column(db.Text, index=False, unique=False, nullable=True)
    created_on = db.Column(db.DateTime(), unique=False, nullable=True)
    num_bugs = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_vulnerabilities = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_code_smells = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_quality = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_analisis = db.Column(db.Integer, index=False, unique=False, nullable=False)

    def __repr__(self):
        return "<Daily {}>".format(self.aplicacion)
    
    def to_dict(self):
        return {
                c.name: str(getattr(self, c.name)) for c in self.__table__.columns
        }

infocodest/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from infocodest.models.users import User


class PasswordForm(FlaskForm):
    email = EmailField("Email Adress", id="email_create", validators=[DataRequired(), Email()])
    submit = SubmitField("Reset Password")


class LoginForm(FlaskForm):
    username = StringField("Username", id="username_login", validators=[DataRequired()])
    password = PasswordField("Password", id="pwd_login", validators=[DataRequired()])
    remember = BooleanField("Remember Password")
    submit = SubmitField("Login")


class RegisterForm(FlaskForm):
    username = StringField(
        "Username",
        id="username_create",
        validators=[DataRequired(), Length(min=4, max=25)],
    )
    email = EmailField(
        "Email Adress", id="email_create", validators=[DataRequired(), Email()]
    )
    password = PasswordField("Password", id="pwd_create", validators=[DataRequired(), Length(8, 72)])
    confirm_password = PasswordField(
        "Confirm Password",
        validators=[
            DataRequired(),
            Length(8, 72),
            EqualTo("password", message="Passwords must match."),
        ],
    )
    submit = SubmitField("Create Account")


    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user is not None:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user is not None:
            self.email.errors.append("Please use a different email address.")
            return False
        if self.password.data != self.confirm_password.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

infocodest/__init__.py
from flask import Flask
from .errorhandlers import error_401, error_404, error_500
from flask_cors import CORS
from .extensions import db, login_manager, migrate, bootstrap, csrf

def register_error_handlers(app):
    # Registering Errorhandler
    app.register_error_handler(401, error_401)
    app.register_error_handler(404, error_404)
    app.register_error_handler(500, error_500)


def register_blueprints(app):
    from infocodest.accounts.views import accounts_bp
    from infocodest.home.views import home_bp
    from infocodest.charts.views import charts_bp
    from infocodest.api.views import api_bp
    
    # Registering blueprints
    app.register_blueprint(accounts_bp)
    app.register_blueprint(home_bp)
    app.register_blueprint(charts_bp, url_prefix='/charts')
    app.register_blueprint(api_bp)


def initialize_plugins(app):
    # Initialize Plugins
    login_manager.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    csrf.init_app(app)
    CORS(app, resources={r"/*": {"origins": "*"}})


def create_app(app_config):
    """Initialize the core application."""
    app = Flask(__name__)
    app.config.from_object(app_config)
    with app.app_context():
        initialize_plugins(app)
        register_blueprints(app)
        register_error_handlers(app)
    return app

infocodest/accounts/__init__.py
from flask import Blueprint

accounts_bp = Blueprint("accounts", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/accounts/views.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user, current_user

from infocodest.extensions import db
from infocodest.accounts import accounts_bp
from infocodest.models.users import User
from infocodest.accounts.forms import LoginForm, RegisterForm, PasswordForm

from infocodest.models.util import verify_pass

# accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("home.home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        
        # Delete user from session
        logout_user()

        return render_template(
            "accounts/register.html",
            msg="Account created successfully.",
            success=True,
            form=form,
        )
    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("home.home"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and verify_pass(form.password.data, user.password):
            login_user(user, remember=form.remember.data)
            print("Logged in successfully.")
            return redirect(url_for("home.home"))
        else:
            flash("Invalid username and/or password.", "danger")
            return render_template("accounts/login.html", form=form, msg="Wrong user or password")
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/password")
def password():
    return render_template("accounts/password.html")


@accounts_bp.route("/password_wtf", methods=["GET", "POST"])
def password_wtf():
    form = PasswordForm()
    if form.validate_on_submit():
        return render_template("accounts/recuperar.html", msg="Se ha enviado un correo a {} para recuperar password.".format(form.email.data))
    return render_template("accounts/password_wtf.html", form=form)


@accounts_bp.route("/user/<username>")
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template("accounts/user.html", user=user)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))

infocodest/api/__init__.py
from flask import Blueprint

api_bp = Blueprint("api", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/api/views.py
from flask import jsonify, url_for, redirect, json, request
from infocodest.api import api_bp
from infocodest.models.metricas import Metrica
from infocodest.models.historico import Historico
from infocodest.models.registros import Registro
from infocodest.models.daily import Daily
from sqlalchemy.sql import func
from datetime import date, timedelta, datetime


@api_bp.route("/api/aplicacion/<aplicacion>")
def historico_project(aplicacion):
    data = {}
    metricas = Metrica.query.filter(Metrica.aplicacion == aplicacion).order_by(Metrica.fecha.asc()).all()
    data["project_name"] = [row.repo for row in metricas]
    data["aplicacion"] = [row.aplicacion for row in metricas]
    data["fecha"] = [row.fecha for row in metricas]
    data["bugs"] = [row.bugs for row in metricas]
    data["vulnerabilities"] = [row.vulnerabilities for row in metricas]
    data["codesmells"] = [row.code_smells for row in metricas]
    return jsonify(data)


@api_bp.route("/api/aplicacion/<project>/<name>")
def historico_name(project, name):
    data = {}
    scores = Historico.query.filter(Historico.repo == name, Historico.aplicacion == project) \
        .order_by(Historico.fecha.asc()).all()
    data["project_name"] = [row.repo for row in scores]
    data["aplicacion"] = [row.aplicacion for row in scores]
    data["fecha"] = [row.fecha for row in scores]
    data["bugs"] = [row.bugs for row in scores]
    data["vulnerabilities"] = [row.vulnerabilities for row in scores]
    data["codesmells"] = [row.code_smells for row in scores]
    return jsonify(data)


@api_bp.route("/api/registro")
def registro():
    limite = request.args.get('limit')
    valor = int(limite)
    fecha_actualizada = datetime.now() - timedelta(days=valor)
    return json.dumps([registro.to_dict() for registro in Registro.query.filter(Registro.created_on >= date(year=fecha_actualizada.year, month=fecha_actualizada.month, day=fecha_actualizada.day))])


@api_bp.route("/api/kpis")
def kpis():
    return json.dumps([registro.to_dict() for registro in Metrica.query.all()])


@api_bp.route("/api/kpis/<project>/<name>")
def kpis_historico_name(project, name):
    data = {}
    scores = Historico.query.filter(Historico.repo == name, Historico.aplicacion == project) \
        .order_by(Historico.fecha.asc()).all()
    data["project_name"] = [row.repo for row in scores]
    data["aplicacion"] = [row.aplicacion for row in scores]
    data["fecha"] = [row.fecha for row in scores]
    data["sqale_debt_ratio"] = [row.sqale_debt_ratio for row in scores]
    data["complexity"] = [row.complexity for row in scores]
    data["duplicated_line_density"] = [row.duplicated_line_density for row in scores]
    data["coverage"] = [row.coverage for row in scores]
    data["ncloc"] = [row.ncloc for row in scores]
    return jsonify(data)


@api_bp.route("/api/rating/<project>/<name>")
def rating_historico_name(project, name):
    data = {}
    scores = Metrica.query.filter(Metrica.repo == name, Metrica.aplicacion == project) \
        .order_by(Metrica.fecha.asc()).all()
    data["project_name"] = [row.repo for row in scores]
    data["aplicacion"] = [row.aplicacion for row in scores]
    data["fecha"] = [row.fecha for row in scores]
    data["sqale_rating"] = [row.sqale_rating for row in scores]
    data["reliability_rating"] = [row.reliability_rating for row in scores]
    data["security_rating"] = [row.security_rating for row in scores]
    return jsonify(data)


@api_bp.route("/api/daily/<aplicacion>")
def daily_aplicacion(aplicacion):
    data = {}
    dailys = Daily.query.filter(Daily.aplicacion == aplicacion) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.aplicacion,
                        Daily.repo,
                        Daily.created_on,
                        func.sum(Daily.num_bugs).label('num_bugs'),
                        func.sum(Daily.num_vulnerabilities).label('num_vulnerabilities'),
                        func.sum(Daily.num_code_smells).label('num_code_smells'),
                        func.sum(Daily.num_analisis).label('num_analisis')
                    ) \
        .all()
    data["project_name"] = [row.repo for row in dailys]
    data["aplicacion"] = [row.aplicacion for row in dailys]
    formato = "%Y-%m-%d"
    data['fecha'] = [row.created_on.strftime(formato) for row in dailys]
    data["bugs"] = [row.num_bugs for row in dailys]
    data["vulnerabilities"] = [row.num_vulnerabilities for row in dailys]
    data["codesmells"] = [row.num_code_smells for row in dailys]
    data["analisis"] = [row.num_analisis for row in dailys]
    return jsonify(data)

# prueba. no funciona
@api_bp.route("/api/daily/metrica/<aplicacion>")
def daily_aplicacion_metrica(aplicacion):
    metrica = request.args.get('metrica')
    campo = "Daily.num_{}".format(metrica)
    print(f'{campo}')
    data = {}
    dailys = Daily.query.filter_by(aplicacion=aplicacion) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.aplicacion,
                        Daily.created_on,
                        func.sum(campo).label('metrica')
                    ) \
        .all()
    
    data["aplicacion"] = [row.aplicacion for row in dailys]
    data['fecha'] = [row.created_on.strftime("%Y-%m-%d") for row in dailys]
    data[metrica] = [row.metrica for row in dailys]
    return jsonify(data)


@api_bp.route("/api/daily/<aplicacion>/<repo>")
def daily_aplicacion_repo(aplicacion, repo):
    data = {}
    dailys = Daily.query.filter(Daily.repo == repo, Daily.aplicacion == aplicacion) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.aplicacion,
                        Daily.repo,
                        Daily.created_on,
                        func.sum(Daily.num_bugs).label('num_bugs'),
                        func.sum(Daily.num_vulnerabilities).label('num_vulnerabilities'),
                        func.sum(Daily.num_code_smells).label('num_code_smells'),
                        func.sum(Daily.num_analisis).label('num_analisis')
                    ) \
        .all()
    data['fecha'] = [row.created_on.strftime("%Y-%m-%d") for row in dailys]
    data["project_name"] = [row.repo for row in dailys]
    data["aplicacion"] = [row.aplicacion for row in dailys]
    data["bugs"] = [row.num_bugs for row in dailys]
    data["vulnerabilities"] = [row.num_vulnerabilities for row in dailys]
    data["codesmells"] = [row.num_code_smells for row in dailys]
    data["analisis"] = [row.num_analisis for row in dailys]
    return jsonify(data)


@api_bp.route("/api/daily/by_proveedor/<proveedor>")
def daily_proveedor(proveedor):
    
    dailys = Daily.query.filter(Daily.proveedor == proveedor) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.proveedor,
                        Daily.created_on,
                        func.sum(Daily.num_bugs).label('num_bugs'),
                        func.sum(Daily.num_vulnerabilities).label('num_vulnerabilities'),
                        func.sum(Daily.num_code_smells).label('num_code_smells'),
                        func.sum(Daily.num_analisis).label('num_analisis')
                    ) \
        .all()
    data = {}
    data['fecha'] = [row.created_on.strftime("%Y-%m-%d") for row in dailys]
    data["proveedor"] = [row.proveedor for row in dailys]
    # data["fecha"] = [row.created_on for row in dailys]
    data["bugs"] = [row.num_bugs for row in dailys]
    data["vulnerabilities"] = [row.num_vulnerabilities for row in dailys]
    data["codesmells"] = [row.num_code_smells for row in dailys]
    data["analisis"] = [row.num_analisis for row in dailys]
    return jsonify(data)

infocodest/charts/__init__.py
from flask import Blueprint

charts_bp = Blueprint("charts", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/charts/views.py
from infocodest.charts import charts_bp
from infocodest.models.metricas import Metrica
from flask import render_template, request
from datetime import datetime
from infocodest.models.database import getRepositorios

@charts_bp.route("/")
def index():
    return render_template('charts/index.html', date=datetime.now())


@charts_bp.route("/charts_test")
def charts_test():
    scores = getRepositorios()
    labels = [row[0] for row in scores]
    values = [row[1] for row in scores]
    return render_template('charts/charts_test.html', labels=labels, values=values, date=datetime.now())


@charts_bp.route("/charts_historico", methods=('GET', 'POST'))
def charts_historico():
    apps = Metrica.query.with_entities(Metrica.aplicacion).distinct().all()
    if request.method == "POST":
        project = request.form["project_name"]
        return render_template(
            'charts/charts_historico.html',
            apps=apps,
            date=datetime.now(),
            project=project,
            success=True
        )
    else:
        return render_template('charts/charts_historico.html', apps=apps, date=datetime.now())

@charts_bp.route("/charts_ejemplo")
def charts_ejemplo():
    return render_template('charts/charts_ejemplo.html', date=datetime.now())

@charts_bp.route("/charts_radar/<project>/<name>")
def charts_radar(project, name):
    return render_template('charts/charts_radar.html', 
                            project=project,
                            name=name,
                            date=datetime.now())

infocodest/home/__init__.py
from flask import Blueprint

home_bp = Blueprint("home", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div id="layoutAuthentication">
  <div id="layoutAuthentication_content">
    <main>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
              <div class="card-header">
                <h3 class="text-center font-weight-light my-4">Login</h3>
                <span class="text-center">
                  {% if msg %}
                  <span class="text-danger"> {{ msg | safe }} </span>
                  {% else %}
                  Add your credentials
                  {% endif %}
                </span>
              </div>
              <div class="card-body">
                <form role="form" method="post" action="">
                  {{ form.hidden_tag() }}
                  <div class="form-floating mb-3">
                    {{ form.username(placeholder="Username", class="form-control") }}
                    <label for="inputUsername">{{ form.username.label }}</label>
                  </div>
                  <div class="form-floating mb-3">
                    {{ form.password(placeholder="Password", class="form-control",
                    type="password") }}
                    <label for="inputPassword">{{ form.password.label }}</label>
                  </div>
                  <div class="form-check mb-3">
                    {{ form.remember(placeholder="RememberPassword", class="form-check-input",
                    id="inputRememberPassword", type="checkbox",
                    value="") }}
                    <label class="form-check-label" for="inputRememberPassword">
                      {{ form.remember.label }}
                    </label>
                  </div>
                  <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                    <a class="small" href="{{ url_for('accounts.password') }}">Forgot Password?</a>
                    {{ form.submit(class="btn btn-primary", type="submit") }}
                  </div>
                </form>
              </div>
              <div class="card-footer text-center py-3">
                <div class="small"><a href="{{ url_for('accounts.register') }}">Need an account? Sign
                    up!</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
  <div id="layoutAuthentication_footer">
    {% include "includes/incl_footer.html" %}
</div>
</div>
{% endblock content %}

infocodest/templates/accounts/password.html
    {% extends "layouts/base-fullscreen.html" %}

{% block title %}Password Recovery{% endblock %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Password Recovery</h3>
                            </div>
                            <div class="card-body">
                                <div class="small mb-3 text-muted">Enter your email address and we will send you a link
                                    to reset your password.</div>
                                <form>
                                    {{ form.hidden_tag() }}
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="inputEmail" type="email"
                                            placeholder="name@example.com" />
                                        <label for="inputEmail">Email address</label>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="{{ url_for('accounts.login')}}">Return to login</a>
                                        <a class="btn btn-primary" href="{{ url_for('accounts.login')}}">Reset
                                            Password</a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center py-3">
                                <div class="small"><a href="{{ url_for('accounts.register')}}">Need an account? Sign
                                        up!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        {% include "includes/incl_footer.html" %}
    </div>
</div>
{% endblock content %}

infocodest/templates/accounts/password_wtf.html
    {% extends "layouts/base-fullscreen.html" %}

{% block title %}Password Recovery{% endblock %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Password Recovery</h3>
                            </div>
                            <div class="card-body">
                                <div class="small mb-3 text-muted">Enter your email address and we will send you a link
                                    to reset your password.</div>
                                <form action="" method="post">
                                    {{ form.hidden_tag() }}
                                    <div class="form-floating mb-3">
                                        {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                                        <label for="inputEmail">{{form.email.label}}</label>
                                        {% for error in form.email.errors %}
                                        <span style="color: red;">[{{ error }}]</span>
                                        {% endfor %}
                                    </div>
                                    <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="{{ url_for('accounts.login')}}">Return to login</a>
                                        {{ form.submit(class="btn btn-primary", type="submit") }}
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center py-3">
                                <div class="small"><a href="{{ url_for('accounts.register')}}">Need an account? Sign
                                        up!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        {% include "includes/incl_footer.html" %}
    </div>
</div>
{% endblock content %}

infocodest/templates/accounts/recuperar.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %}Password Recovery{% endblock %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Password Recovery</h3>
                            </div>
                            <div class="card-body">
                                <div class="small mb-3 text-muted">{{ msg }}</div>
                            </div>
                            <div class="card-footer text-center py-3">
                                <div class="small"><a href="{{ url_for('accounts.login')}}">Return to login</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        {% include "includes/incl_footer.html" %}
    </div>
</div>
{% endblock content %}

infocodest/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div id="layoutAuthentication">
  <div id="layoutAuthentication_content">
    <main>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
              <div class="card-header">
                <h3 class="text-center font-weight-light my-4">Create Account</h3>
                <span class="text-center">
                  {% if msg %}
                  {{ msg | safe }}
                  {% else %}
                  Add your credentials
                  {% endif %}
                </span>
              </div>
              <div class="card-body">
                {% if success %}
                <div class="text-center">
                  <a href="{{ url_for('accounts.login') }}" class="btn btn-primary">Sign IN</a>
                </div>
                {% else %}
                <form action="" method="post">
                  {{ form.hidden_tag() }}
                  <div class="form-floating mb-3">
                    {{ form.username(placeholder="Username", class="form-control", type="text") }}
                    <label for="inputUserName">{{form.username.label}}</label>
                    {% for error in form.username.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                  </div>
                  <div class="form-floating mb-3">
                    {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                    <label for="inputEmail">{{form.email.label}}</label>
                    {% for error in form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                  </div>
                  <div class="row mb-3">
                    <div class="col-md-6">
                      <div class="form-floating mb-3 mb-md-0">
                        {{ form.password(placeholder="Password", class="form-control", type="password") }}
                        <!-- <input class="form-control" id="inputPassword" type="password" placeholder="Create a password" /> -->
                        <label for="inputPassword">{{form.password.label}}</label>
                        {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating mb-3 mb-md-0">
                        {{ form.confirm_password(placeholder = "Confirm Password", class="form-control",
                        type="password") }}
                        <!-- <input class="form-control" id="inputPasswordConfirm" type="password" placeholder="Confirm password" /> -->
                        <label for="inputPasswordConfirm">{{form.confirm_password.label}}</label>
                        {% for error in form.confirm_password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                  <div class="mt-4 mb-0">
                    <div class="d-grid">
                      <!-- <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">Create Account</button> -->
                      {{ form.submit(class="btn btn-primary shadow-2 mb-4", type="submit") }}
                    </div>
<!--
                    <div class="d-grid"><a class="btn btn-primary btn-block" href="{{ url_for('accounts.register')}}">Create Account</a></div>
-->
                  </div>
                </form>
                {% endif %}
              </div>
              <div class="card-footer text-center py-3">
                <div class="small"><a href="{{ url_for('accounts.login')}}">Have an account? Go to login</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
  <div id="layoutAuthentication_footer">
    {% include "includes/incl_footer.html" %}
  </div>
</div>
{% endblock content %}

infocodest/templates/accounts/user.html
{% extends "layouts/base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block title %}User Page{% endblock %}

{% block content %}
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
      <h1 class="mt-4">Page User</h1>
      <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"></li>
      </ol>
        <h1 class="text-center">Welcome {{current_user.username}}!</h1>
        <h2 class="text-center">{{ current_user.email }} </h2>
        <h3 class="text-center">Usuario Creado: {{ user.created_on }} </h3>
        <h3 class="text-center">Admin ? {{ user.is_admin }} </h3>
    </div>
  </main>
  {% include "includes/incl_footer.html" %}
</div>
{% endblock content %}