infocodest/models/daily.py
"""Data models."""
# from infocodest import db
from infocodest.extensions import db


class Daily(db.Model):
    """Data model for user accounts."""

    __tablename__ = "daily"

    id = db.Column(db.Integer, primary_key=True)
    aplicacion = db.Column(db.String(64), index=False, unique=True, nullable=False)
    repo = db.Column(db.Integer, index=True, unique=True, nullable=False)
    proveedor = db.Column(db.Text, index=False, unique=False, nullable=True)
    created_on = db.Column(db.DateTime(), unique=False, nullable=True)
    num_bugs = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_vulnerabilities = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_code_smells = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_quality = db.Column(db.Integer, index=False, unique=False, nullable=False)
    num_analisis = db.Column(db.Integer, index=False, unique=False, nullable=False)

    def __repr__(self):
        return "<Daily {}>".format(self.aplicacion)
    
    def to_dict(self):
        return {
                c.name: str(getattr(self, c.name)) for c in self.__table__.columns
        }

infocodest/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from infocodest.models.users import User


class PasswordForm(FlaskForm):
    email = EmailField("Email Adress", id="email_create", validators=[DataRequired(), Email()])
    submit = SubmitField("Reset Password")


class LoginForm(FlaskForm):
    username = StringField("Username", id="username_login", validators=[DataRequired()])
    password = PasswordField("Password", id="pwd_login", validators=[DataRequired()])
    remember = BooleanField("Remember Password")
    submit = SubmitField("Login")


class RegisterForm(FlaskForm):
    username = StringField(
        "Username",
        id="username_create",
        validators=[DataRequired(), Length(min=4, max=25)],
    )
    email = EmailField(
        "Email Adress", id="email_create", validators=[DataRequired(), Email()]
    )
    password = PasswordField("Password", id="pwd_create", validators=[DataRequired(), Length(8, 72)])
    confirm_password = PasswordField(
        "Confirm Password",
        validators=[
            DataRequired(),
            Length(8, 72),
            EqualTo("password", message="Passwords must match."),
        ],
    )
    submit = SubmitField("Create Account")


    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user is not None:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user is not None:
            self.email.errors.append("Please use a different email address.")
            return False
        if self.password.data != self.confirm_password.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

infocodest/__init__.py
from flask import Flask
from .errorhandlers import error_401, error_404, error_500
from flask_cors import CORS
from .extensions import db, login_manager, migrate, bootstrap, csrf

def register_error_handlers(app):
    # Registering Errorhandler
    app.register_error_handler(401, error_401)
    app.register_error_handler(404, error_404)
    app.register_error_handler(500, error_500)


def register_blueprints(app):
    from infocodest.accounts.views import accounts_bp
    from infocodest.home.views import home_bp
    from infocodest.charts.views import charts_bp
    from infocodest.api.views import api_bp
    
    # Registering blueprints
    app.register_blueprint(accounts_bp)
    app.register_blueprint(home_bp)
    app.register_blueprint(charts_bp, url_prefix='/charts')
    app.register_blueprint(api_bp)


def initialize_plugins(app):
    # Initialize Plugins
    login_manager.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    csrf.init_app(app)
    CORS(app, resources={r"/*": {"origins": "*"}})


def create_app(app_config):
    """Initialize the core application."""
    app = Flask(__name__)
    app.config.from_object(app_config)
    with app.app_context():
        initialize_plugins(app)
        register_blueprints(app)
        register_error_handlers(app)
    return app

infocodest/accounts/__init__.py
from flask import Blueprint

accounts_bp = Blueprint("accounts", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/accounts/views.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user, current_user

from infocodest.extensions import db
from infocodest.accounts import accounts_bp
from infocodest.models.users import User
from infocodest.accounts.forms import LoginForm, RegisterForm, PasswordForm

from infocodest.models.util import verify_pass

# accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("home.home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        
        # Delete user from session
        logout_user()

        return render_template(
            "accounts/register.html",
            msg="Account created successfully.",
            success=True,
            form=form,
        )
    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("home.home"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and verify_pass(form.password.data, user.password):
            login_user(user, remember=form.remember.data)
            print("Logged in successfully.")
            return redirect(url_for("home.home"))
        else:
            flash("Invalid username and/or password.", "danger")
            return render_template("accounts/login.html", form=form, msg="Wrong user or password")
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/password")
def password():
    return render_template("accounts/password.html")


@accounts_bp.route("/password_wtf", methods=["GET", "POST"])
def password_wtf():
    form = PasswordForm()
    if form.validate_on_submit():
        return render_template("accounts/recuperar.html", msg="Se ha enviado un correo a {} para recuperar password.".format(form.email.data))
    return render_template("accounts/password_wtf.html", form=form)


@accounts_bp.route("/user/<username>")
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template("accounts/user.html", user=user)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))

infocodest/api/__init__.py
from flask import Blueprint

api_bp = Blueprint("api", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/api/views.py
from flask import jsonify, url_for, redirect, json, request
from infocodest.api import api_bp
from infocodest.models.metricas import Metrica
from infocodest.models.historico import Historico
from infocodest.models.registros import Registro
from infocodest.models.daily import Daily
from sqlalchemy.sql import func
from datetime import date, timedelta, datetime


@api_bp.route("/api/aplicacion/<aplicacion>")
def historico_project(aplicacion):
    data = {}
    metricas = Metrica.query.filter(Metrica.aplicacion == aplicacion).order_by(Metrica.fecha.asc()).all()
    data["project_name"] = [row.repo for row in metricas]
    data["aplicacion"] = [row.aplicacion for row in metricas]
    data["fecha"] = [row.fecha for row in metricas]
    data["bugs"] = [row.bugs for row in metricas]
    data["vulnerabilities"] = [row.vulnerabilities for row in metricas]
    data["codesmells"] = [row.code_smells for row in metricas]
    return jsonify(data)


@api_bp.route("/api/aplicacion/<project>/<name>")
def historico_name(project, name):
    data = {}
    scores = Historico.query.filter(Historico.repo == name, Historico.aplicacion == project) \
        .order_by(Historico.fecha.asc()).all()
    data["project_name"] = [row.repo for row in scores]
    data["aplicacion"] = [row.aplicacion for row in scores]
    data["fecha"] = [row.fecha for row in scores]
    data["bugs"] = [row.bugs for row in scores]
    data["vulnerabilities"] = [row.vulnerabilities for row in scores]
    data["codesmells"] = [row.code_smells for row in scores]
    return jsonify(data)


@api_bp.route("/api/registro")
def registro():
    limite = request.args.get('limit')
    valor = int(limite)
    fecha_actualizada = datetime.now() - timedelta(days=valor)
    return json.dumps([registro.to_dict() for registro in Registro.query.filter(Registro.created_on >= date(year=fecha_actualizada.year, month=fecha_actualizada.month, day=fecha_actualizada.day))])


@api_bp.route("/api/kpis")
def kpis():
    return json.dumps([registro.to_dict() for registro in Metrica.query.all()])


@api_bp.route("/api/kpis/<project>/<name>")
def kpis_historico_name(project, name):
    data = {}
    scores = Historico.query.filter(Historico.repo == name, Historico.aplicacion == project) \
        .order_by(Historico.fecha.asc()).all()
    data["project_name"] = [row.repo for row in scores]
    data["aplicacion"] = [row.aplicacion for row in scores]
    data["fecha"] = [row.fecha for row in scores]
    data["sqale_debt_ratio"] = [row.sqale_debt_ratio for row in scores]
    data["complexity"] = [row.complexity for row in scores]
    data["duplicated_line_density"] = [row.duplicated_line_density for row in scores]
    data["coverage"] = [row.coverage for row in scores]
    data["ncloc"] = [row.ncloc for row in scores]
    return jsonify(data)


@api_bp.route("/api/rating/<project>/<name>")
def rating_historico_name(project, name):
    data = {}
    scores = Metrica.query.filter(Metrica.repo == name, Metrica.aplicacion == project) \
        .order_by(Metrica.fecha.asc()).all()
    data["project_name"] = [row.repo for row in scores]
    data["aplicacion"] = [row.aplicacion for row in scores]
    data["fecha"] = [row.fecha for row in scores]
    data["sqale_rating"] = [row.sqale_rating for row in scores]
    data["reliability_rating"] = [row.reliability_rating for row in scores]
    data["security_rating"] = [row.security_rating for row in scores]
    return jsonify(data)


@api_bp.route("/api/daily/<aplicacion>")
def daily_aplicacion(aplicacion):
    data = {}
    dailys = Daily.query.filter(Daily.aplicacion == aplicacion) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.aplicacion,
                        Daily.repo,
                        Daily.created_on,
                        func.sum(Daily.num_bugs).label('num_bugs'),
                        func.sum(Daily.num_vulnerabilities).label('num_vulnerabilities'),
                        func.sum(Daily.num_code_smells).label('num_code_smells'),
                        func.sum(Daily.num_analisis).label('num_analisis')
                    ) \
        .all()
    data["project_name"] = [row.repo for row in dailys]
    data["aplicacion"] = [row.aplicacion for row in dailys]
    formato = "%Y-%m-%d"
    data['fecha'] = [row.created_on.strftime(formato) for row in dailys]
    data["bugs"] = [row.num_bugs for row in dailys]
    data["vulnerabilities"] = [row.num_vulnerabilities for row in dailys]
    data["codesmells"] = [row.num_code_smells for row in dailys]
    data["analisis"] = [row.num_analisis for row in dailys]
    return jsonify(data)

# prueba. no funciona
@api_bp.route("/api/daily/metrica/<aplicacion>")
def daily_aplicacion_metrica(aplicacion):
    metrica = request.args.get('metrica')
    campo = "Daily.num_{}".format(metrica)
    print(f'{campo}')
    data = {}
    dailys = Daily.query.filter_by(aplicacion=aplicacion) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.aplicacion,
                        Daily.created_on,
                        func.sum(campo).label('metrica')
                    ) \
        .all()
    
    data["aplicacion"] = [row.aplicacion for row in dailys]
    data['fecha'] = [row.created_on.strftime("%Y-%m-%d") for row in dailys]
    data[metrica] = [row.metrica for row in dailys]
    return jsonify(data)


@api_bp.route("/api/daily/<aplicacion>/<repo>")
def daily_aplicacion_repo(aplicacion, repo):
    data = {}
    dailys = Daily.query.filter(Daily.repo == repo, Daily.aplicacion == aplicacion) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.aplicacion,
                        Daily.repo,
                        Daily.created_on,
                        func.sum(Daily.num_bugs).label('num_bugs'),
                        func.sum(Daily.num_vulnerabilities).label('num_vulnerabilities'),
                        func.sum(Daily.num_code_smells).label('num_code_smells'),
                        func.sum(Daily.num_analisis).label('num_analisis')
                    ) \
        .all()
    data['fecha'] = [row.created_on.strftime("%Y-%m-%d") for row in dailys]
    data["project_name"] = [row.repo for row in dailys]
    data["aplicacion"] = [row.aplicacion for row in dailys]
    data["bugs"] = [row.num_bugs for row in dailys]
    data["vulnerabilities"] = [row.num_vulnerabilities for row in dailys]
    data["codesmells"] = [row.num_code_smells for row in dailys]
    data["analisis"] = [row.num_analisis for row in dailys]
    return jsonify(data)


@api_bp.route("/api/daily/by_proveedor/<proveedor>")
def daily_proveedor(proveedor):
    
    dailys = Daily.query.filter(Daily.proveedor == proveedor) \
        .group_by(Daily.created_on) \
        .order_by(Daily.created_on.asc()) \
        .with_entities( Daily.proveedor,
                        Daily.created_on,
                        func.sum(Daily.num_bugs).label('num_bugs'),
                        func.sum(Daily.num_vulnerabilities).label('num_vulnerabilities'),
                        func.sum(Daily.num_code_smells).label('num_code_smells'),
                        func.sum(Daily.num_analisis).label('num_analisis')
                    ) \
        .all()
    data = {}
    data['fecha'] = [row.created_on.strftime("%Y-%m-%d") for row in dailys]
    data["proveedor"] = [row.proveedor for row in dailys]
    # data["fecha"] = [row.created_on for row in dailys]
    data["bugs"] = [row.num_bugs for row in dailys]
    data["vulnerabilities"] = [row.num_vulnerabilities for row in dailys]
    data["codesmells"] = [row.num_code_smells for row in dailys]
    data["analisis"] = [row.num_analisis for row in dailys]
    return jsonify(data)

infocodest/charts/__init__.py
from flask import Blueprint

charts_bp = Blueprint("charts", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/charts/views.py
from infocodest.charts import charts_bp
from infocodest.models.metricas import Metrica
from flask import render_template, request
from datetime import datetime
from infocodest.models.database import getRepositorios

@charts_bp.route("/")
def index():
    return render_template('charts/index.html', date=datetime.now())


@charts_bp.route("/charts_test")
def charts_test():
    scores = getRepositorios()
    labels = [row[0] for row in scores]
    values = [row[1] for row in scores]
    return render_template('charts/charts_test.html', labels=labels, values=values, date=datetime.now())


@charts_bp.route("/charts_historico", methods=('GET', 'POST'))
def charts_historico():
    apps = Metrica.query.with_entities(Metrica.aplicacion).distinct().all()
    if request.method == "POST":
        project = request.form["project_name"]
        return render_template(
            'charts/charts_historico.html',
            apps=apps,
            date=datetime.now(),
            project=project,
            success=True
        )
    else:
        return render_template('charts/charts_historico.html', apps=apps, date=datetime.now())

@charts_bp.route("/charts_ejemplo")
def charts_ejemplo():
    return render_template('charts/charts_ejemplo.html', date=datetime.now())

@charts_bp.route("/charts_radar/<project>/<name>")
def charts_radar(project, name):
    return render_template('charts/charts_radar.html', 
                            project=project,
                            name=name,
                            date=datetime.now())

infocodest/home/__init__.py
from flask import Blueprint

home_bp = Blueprint("home", __name__, template_folder="templates", static_folder="static")

from . import views

infocodest/templates/includes/incl_layoutSidenav_nav copy.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{{ url_for('home.home') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">
                    <hr style="color: rgb(109, 106, 106); background-color: rgb(245, 240, 240); width:75%;" />
                </div>
                <div class="sb-sidenav-menu-heading"></div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseMetricas"
                    aria-expanded="false" aria-controls="collapseMetricas">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Metricas
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseMetricas" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.metricas') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Métricas
                        </a>
                        <a class="nav-link" href="{{ url_for('home.proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Métricas por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Métricas Histórico
                        </a>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading"></div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseKPIs"
                    aria-expanded="false" aria-controls="collapseKPIs">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    SLAs - SLOs
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseKPIs" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.kpis') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            KPIs
                        </a>
                        <a class="nav-link" href="{{ url_for('home.kpis_proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            KPIs por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.kpis_historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            KPIs Histórico
                        </a>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading"></div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseSTATs"
                    aria-expanded="false" aria-controls="collapseKPIs">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Estadísticas
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseSTATs" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.stats') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            STATs
                        </a>
                        <a class="nav-link" href="{{ url_for('home.stats_proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            STATs por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.stats_historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            STATs Histórico
                        </a>
                    </nav>
                </div>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            {% if current_user.is_authenticated %}
                {{ current_user.username }}
            {% endif %}
        </div>
    </nav>
</div>

infocodest/templates/includes/incl_layoutSidenav_nav.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{{ url_for('home.home') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">
                    <hr style="color: rgb(150, 10, 10); background-color: rgb(245, 240, 240); width:75%;" />
                </div>
                <div class="sb-sidenav-menu-heading"></div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseMetricas"
                    aria-expanded="false" aria-controls="collapseMetricas">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Metricas
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseMetricas" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.metricas') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Métricas
                        </a>
                        <a class="nav-link" href="{{ url_for('home.proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Métricas por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Métricas Histórico
                        </a>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading"></div>
                <!--
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseKPIs"
                    aria-expanded="false" aria-controls="collapseKPIs">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    SLAs - SLOs
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseKPIs" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.kpis') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            KPIs
                        </a>
                        <a class="nav-link" href="{{ url_for('home.kpis_proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            KPIs por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.kpis_historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            KPIs Histórico
                        </a>
                    </nav>
                </div>
                -->
                <div class="sb-sidenav-menu-heading"></div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseSTATs"
                    aria-expanded="false" aria-controls="collapseKPIs">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Estadísticas
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseSTATs" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.stats') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            STATs
                        </a>
                        <a class="nav-link" href="{{ url_for('home.stats_proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            STATs por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.stats_historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            STATs Histórico
                        </a>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading"></div>
                <!--
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseDailys"
                    aria-expanded="false" aria-controls="collapseDaily">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Dailys
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseDailys" aria-labelledby="headingOne"
                    data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url_for('home.dailys') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Dailys
                        </a>
                        <a class="nav-link" href="{{ url_for('home.dailys_proveedores') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Dailys por proveedor
                        </a>
                        <a class="nav-link" href="{{ url_for('home.dailys_historico') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Dailys Histórico
                        </a>
                    </nav>
                </div>
                -->
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            {% if current_user.is_authenticated %}
                {{ current_user.username }}
            {% endif %}
        </div>
    </nav>
</div>

infocodest/templates/includes/incl_navbar.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{{ url_for('home.home') }}">INFOCODES Dashboard</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{ url_for('accounts.user', username=current_user.username) }}">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li>
                    <hr class="dropdown-divider" />
                </li>
                <li><a class="dropdown-item" href="{{ url_for('accounts.logout') }}">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>